import type { Metadata } from "next";
import "./globals.css";
import { UserProvider  } from "@/context/UserProvider";

export const metadata: Metadata = {
  title: "Vox Mundi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`min-h-screen bg-background text-foreground max-w-[1280px] mx-auto font-inter`}
      >
        <UserProvider>
          {children}
        </UserProvider>
      </body>
    </html>
  );
}
