# Generated by Django 5.2.5 on 2025-10-01 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True, null=True)),
                ('display_reviews_publicly', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.RenameIndex(
            model_name='person',
            new_name='person_name_idx',
            old_name='core_person_family__e0e69f_idx',
        ),
        migrations.RenameIndex(
            model_name='universalitem',
            new_name='universal_item_idx',
            old_name='core_univer_content_34bb10_idx',
        ),
        migrations.RenameIndex(
            model_name='userartwork',
            new_name='user_artwork_idx',
            old_name='core_userar_user_id_365846_idx',
        ),
        migrations.RenameIndex(
            model_name='userbook',
            new_name='user_book_idx',
            old_name='core_userbo_user_id_4fb54c_idx',
        ),
        migrations.RenameIndex(
            model_name='userfilm',
            new_name='user_film_idx',
            old_name='core_userfi_user_id_583050_idx',
        ),
        migrations.RenameIndex(
            model_name='userhistoryevent',
            new_name='user_event_idx',
            old_name='core_userhi_user_id_2b737d_idx',
        ),
        migrations.RenameIndex(
            model_name='usermusicpiece',
            new_name='user_music_idx',
            old_name='core_usermu_user_id_7de088_idx',
        ),
        migrations.AddField(
            model_name='artwork',
            name='wikidata_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='calendardate',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=20),
        ),
        migrations.AddField(
            model_name='film',
            name='tmdb_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='historyevent',
            name='wikidata_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='langlesson',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=20),
        ),
        migrations.AddField(
            model_name='musicpiece',
            name='musicbrainz_id',
            field=models.CharField(blank=True, max_length=36, unique=True),
        ),
        migrations.AddField(
            model_name='person',
            name='wikidata_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=20),
        ),
        migrations.AddField(
            model_name='userartwork',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=20),
        ),
        migrations.AddField(
            model_name='userbook',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=20),
        ),
        migrations.AddField(
            model_name='userfilm',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=20),
        ),
        migrations.AddField(
            model_name='userhistoryevent',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=20),
        ),
        migrations.AddField(
            model_name='usermusicpiece',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddIndex(
            model_name='artwork',
            index=models.Index(fields=['wikidata_id'], name='artwork_wikidata_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['isbn'], name='book_isbn_idx'),
        ),
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['tmdb_id'], name='film_tmdb_idx'),
        ),
        migrations.AddIndex(
            model_name='historyevent',
            index=models.Index(fields=['wikidata_id'], name='event_wikidata_idx'),
        ),
        migrations.AddIndex(
            model_name='musicpiece',
            index=models.Index(fields=['musicbrainz_id'], name='music_musicbrainz_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['wikidata_id'], name='person_wikidata_idx'),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_cultures',
            field=models.ManyToManyField(blank=True, related_name='preferred_by', to='core.culture'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user'], name='core_profil_user_id_155486_idx'),
        ),
    ]
