# Generated by Django 5.2.5 on 2025-10-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfilm',
            name='cast',
        ),
        migrations.RemoveField(
            model_name='userfilm',
            name='crew',
        ),
        migrations.AddField(
            model_name='userfilm',
            name='cast',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='userfilm',
            name='crew',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
