# Generated by Django 5.2.5 on 2025-10-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_userfilm_cast_remove_userfilm_crew_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='external_links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='wikidata_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='external_links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='external_links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='film',
            name='tmdb_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='historyevent',
            name='external_links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='historyevent',
            name='wikidata_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mappin',
            name='external_links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='musicpiece',
            name='external_links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='musicpiece',
            name='musicbrainz_id',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='external_links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='userfilm',
            name='cast',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='userfilm',
            name='crew',
            field=models.JSONField(default=list),
        ),
    ]
