# Generated by Django 5.2.5 on 2025-10-06 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_artwork_external_links_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='culture',
            name='core_cultur_user_id_eb3b70_idx',
        ),
        migrations.RemoveIndex(
            model_name='period',
            name='core_period_culture_508165_idx',
        ),
        migrations.RemoveField(
            model_name='period',
            name='section',
        ),
        migrations.AddField(
            model_name='culture',
            name='shared_group_key',
            field=models.SlugField(blank=True, default='', help_text='Canonical key linking related cultures across users'),
        ),
        migrations.AddField(
            model_name='period',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='core.category'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='culture',
            index=models.Index(fields=['user', 'code', 'shared_group_key'], name='core_cultur_user_id_fbf182_idx'),
        ),
        migrations.AddIndex(
            model_name='period',
            index=models.Index(fields=['culture', 'category'], name='core_period_culture_a4e6a5_idx'),
        ),
    ]
