# Generated by Django 5.2.5 on 2025-10-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_culture_core_cultur_user_id_eb3b70_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
