# Generated by Django 5.2.5 on 2025-10-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_period_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='culture',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=20),
        ),
    ]
