# Generated by Django 5.2.5 on 2025-10-07 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_culture_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappin',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=20),
        ),
    ]
