# Generated by Django 5.2.5 on 2025-10-07 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_mappin_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='creator_string',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='creator_string',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='creator_string',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historyevent',
            name='creator_string',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='musicpiece',
            name='creator_string',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
