# Generated by Django 5.2.5 on 2025-10-07 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0009_artwork_creator_string_book_creator_string_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='universalitem',
            new_name='core_univer_content_34bb10_idx',
            old_name='universal_item_idx',
        ),
        migrations.RemoveField(
            model_name='userfilm',
            name='background_pic',
        ),
        migrations.RemoveField(
            model_name='userfilm',
            name='cast',
        ),
        migrations.RemoveField(
            model_name='userfilm',
            name='color',
        ),
        migrations.RemoveField(
            model_name='userfilm',
            name='crew',
        ),
        migrations.RemoveField(
            model_name='userfilm',
            name='medium',
        ),
        migrations.RemoveField(
            model_name='userfilm',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='userfilm',
            name='sound',
        ),
        migrations.AddField(
            model_name='film',
            name='background_pic',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='cast',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='film',
            name='crew',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='film',
            name='poster',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universalitem',
            name='creator_string',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddIndex(
            model_name='universalitem',
            index=models.Index(fields=['title'], name='core_univer_title_4defa7_idx'),
        ),
        migrations.AddIndex(
            model_name='universalitem',
            index=models.Index(fields=['type'], name='core_univer_type_da3292_idx'),
        ),
        migrations.AddIndex(
            model_name='universalitem',
            index=models.Index(fields=['creator_string'], name='core_univer_creator_aec6cd_idx'),
        ),
    ]
