# Generated by Django 5.2.5 on 2025-10-08 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_book_genre_book_industry_rating_book_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='volume',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='series',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
