# Generated by Django 5.2.5 on 2025-10-08 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_book_volume_alter_book_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='userartwork',
            name='owned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermusicpiece',
            name='learned',
            field=models.BooleanField(default=False),
        ),
    ]
