# Generated by Django 5.2.5 on 2025-10-08 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_userartwork_owned_usermusicpiece_learned'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=20)),
                ('type', models.CharField(blank=True, choices=[('books', 'Books'), ('films', 'Films'), ('artworks', 'Artworks'), ('music', 'Music'), ('events', 'History Events')], max_length=100, null=True)),
                ('cultures', models.ManyToManyField(blank=True, related_name='lists', to='core.culture')),
                ('items', models.ManyToManyField(blank=True, related_name='in_lists', to='core.universalitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Lists',
                'indexes': [models.Index(fields=['user', 'name'], name='list_user_name_idx')],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
