# Generated by Django 5.2.5 on 2025-10-08 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappin',
            name='date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.dateestimate'),
        ),
        migrations.AddField(
            model_name='mappin',
            name='happened',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mappin',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mappin',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mappin',
            name='significance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mappin',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
