# Generated by Django 5.2.5 on 2025-10-08 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_mappin_date_mappin_happened_mappin_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='themes',
        ),
        migrations.RemoveField(
            model_name='historyevent',
            name='period',
        ),
        migrations.RemoveField(
            model_name='historyevent',
            name='significance_level',
        ),
        migrations.RemoveField(
            model_name='historyevent',
            name='sources',
        ),
        migrations.AddField(
            model_name='userartwork',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userartwork',
            name='themes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userhistoryevent',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.period'),
        ),
        migrations.AddField(
            model_name='userhistoryevent',
            name='significance_level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userhistoryevent',
            name='sources',
            field=models.TextField(blank=True),
        ),
    ]
