# Generated by Django 5.2.5 on 2025-10-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_artwork_themes_remove_historyevent_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='period',
            name='short_intro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
