# Generated by Django 5.2.5 on 2025-10-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_period_desc_alter_period_short_intro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfilm',
            old_name='awards_won',
            new_name='awards',
        ),
        migrations.AlterField(
            model_name='userfilm',
            name='watch_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
