# Generated by Django 5.2.5 on 2025-10-08 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_usermusicartist'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermusicartist',
            name='genres',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='usermusicartist',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
