# Generated by Django 5.2.5 on 2025-10-08 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_usermusicartist_genres_alter_usermusicartist_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhistoryevent',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userhistoryevent',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='associated_culture',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historyevent',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='type',
            field=models.CharField(blank=True, choices=[('books', 'Books'), ('films', 'Films'), ('artworks', 'Artworks'), ('music', 'Music'), ('events', 'History Events'), ('mixed', 'Mixed')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userartwork',
            name='themes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
