# Generated by Django 5.2.5 on 2025-10-09 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_userhistoryevent_photo_userhistoryevent_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
