# Generated by Django 5.2.5 on 2025-10-09 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_period_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historyevent',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='historyevent',
            name='date',
        ),
        migrations.RemoveField(
            model_name='historyevent',
            name='tags',
        ),
        migrations.RemoveIndex(
            model_name='userhistoryevent',
            name='user_event_idx',
        ),
        migrations.RemoveField(
            model_name='userhistoryevent',
            name='universal_item',
        ),
        migrations.AddField(
            model_name='userhistoryevent',
            name='alt_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userhistoryevent',
            name='date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.dateestimate'),
        ),
        migrations.AddField(
            model_name='userhistoryevent',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userhistoryevent',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userhistoryevent',
            name='type',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='userhistoryevent',
            index=models.Index(fields=['user'], name='user_event_idx'),
        ),
        migrations.DeleteModel(
            name='HistoryEvent',
        ),
    ]
