# Generated by Django 5.2.5 on 2025-10-11 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_historyevent_creator_remove_historyevent_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='date',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.dateestimate'),
        ),
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.dateestimate'),
        ),
        migrations.AlterField(
            model_name='film',
            name='date',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.dateestimate'),
        ),
        migrations.AlterField(
            model_name='musicpiece',
            name='date',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.dateestimate'),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='births', to='core.dateestimate'),
        ),
        migrations.AlterField(
            model_name='person',
            name='death_date',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deaths', to='core.dateestimate'),
        ),
        migrations.AlterField(
            model_name='userhistoryevent',
            name='date',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_history_event', to='core.dateestimate'),
        ),
    ]
