# Generated by Django 5.2.5 on 2025-10-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_artwork_date_alter_book_date_alter_film_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendardate',
            name='isAnnual',
            field=models.BooleanField(default=False),
        ),
    ]
