# Generated by Django 5.2.5 on 2025-10-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_calendardate_isannual'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendardate',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
