# Generated by Django 5.2.5 on 2025-10-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_calendardate_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='extra_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='intro_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='overview_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='type',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
