# Generated by Django 5.2.5 on 2025-10-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_pagecontent_extra_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='type',
            field=models.JSONField(default=list),
        ),
    ]
