# Generated by Django 5.2.5 on 2025-10-17 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_recipe_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='type',
            new_name='types',
        ),
    ]
