# Generated by Django 5.2.5 on 2025-10-17 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_rename_type_recipe_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendardate',
            name='reference_system',
            field=models.CharField(choices=[('gregorian', 'Gregorian'), ('egyptian', 'Egyptian'), ('islamic', 'Islamic')], default='gregorian', max_length=50),
        ),
    ]
