# Generated by Django 5.2.5 on 2025-10-18 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_calendardate_reference_system'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='universalitem',
            name='core_univer_content_34bb10_idx',
        ),
        migrations.RemoveField(
            model_name='universalitem',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='universalitem',
            name='cultures',
        ),
        migrations.RemoveField(
            model_name='universalitem',
            name='object_id',
        ),
        migrations.AddField(
            model_name='film',
            name='industry_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='universal_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='film', to='core.universalitem'),
        ),
        migrations.AddField(
            model_name='universalitem',
            name='external_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='film',
            name='genre',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
