# Generated by Django 5.2.5 on 2025-10-19 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_universalitem_core_univer_content_34bb10_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfilm',
            name='awards',
        ),
    ]
