# Generated by Django 5.2.5 on 2025-10-19 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_userfilm_awards'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfilm',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_films', to='core.period'),
        ),
    ]
