# Generated by Django 5.2.5 on 2025-10-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_calendardate_cultures_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendardate',
            name='cultures',
            field=models.ManyToManyField(related_name='%(class)s_items', to='core.culture'),
        ),
        migrations.AlterField(
            model_name='langlesson',
            name='cultures',
            field=models.ManyToManyField(related_name='%(class)s_items', to='core.culture'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cultures',
            field=models.ManyToManyField(related_name='%(class)s_items', to='core.culture'),
        ),
        migrations.AlterField(
            model_name='userartwork',
            name='cultures',
            field=models.ManyToManyField(related_name='%(class)s_items', to='core.culture'),
        ),
        migrations.AlterField(
            model_name='userbook',
            name='cultures',
            field=models.ManyToManyField(related_name='%(class)s_items', to='core.culture'),
        ),
        migrations.AlterField(
            model_name='userfilm',
            name='cultures',
            field=models.ManyToManyField(related_name='%(class)s_items', to='core.culture'),
        ),
        migrations.AlterField(
            model_name='userhistoryevent',
            name='cultures',
            field=models.ManyToManyField(related_name='%(class)s_items', to='core.culture'),
        ),
        migrations.AlterField(
            model_name='usermusicartist',
            name='cultures',
            field=models.ManyToManyField(related_name='%(class)s_items', to='core.culture'),
        ),
        migrations.AlterField(
            model_name='usermusicpiece',
            name='cultures',
            field=models.ManyToManyField(related_name='%(class)s_items', to='core.culture'),
        ),
    ]
