# Generated by Django 5.2.5 on 2025-10-23 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_calendardate_cultures_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbook',
            name='is_history',
        ),
        migrations.RemoveField(
            model_name='userbook',
            name='location',
        ),
        migrations.AddField(
            model_name='artwork',
            name='medium',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='owner',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userfilm',
            name='universal_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_films', to='core.universalitem'),
        ),
    ]
