# Generated by Django 5.2.5 on 2025-10-24 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_remove_userbook_is_history_remove_userbook_location_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='book',
            name='book_isbn_idx',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='isbn',
            new_name='ol_id',
        ),
        migrations.RemoveField(
            model_name='book',
            name='language',
        ),
        migrations.AddField(
            model_name='book',
            name='languages',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['ol_id'], name='book_ol_id_idx'),
        ),
    ]
