# Generated by Django 5.2.5 on 2025-10-25 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_remove_book_book_isbn_idx_rename_isbn_book_ol_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='universal_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book', to='core.universalitem'),
        ),
    ]
