# Generated by Django 5.2.5 on 2025-10-25 20:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_book_universal_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='isbn',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='userbook',
            unique_together={('user', 'isbn')},
        ),
    ]
