# Generated by Django 5.2.5 on 2025-10-25 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_userbook_isbn_alter_userbook_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_books', to='core.period'),
        ),
    ]
