# Generated by Django 5.2.5 on 2025-10-27 11:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_userbook_period'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='date',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='musicpiece',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='musicpiece',
            name='date',
        ),
        migrations.RemoveField(
            model_name='musicpiece',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='userartwork',
            name='cultures',
        ),
        migrations.RemoveField(
            model_name='userartwork',
            name='universal_item',
        ),
        migrations.RemoveField(
            model_name='userartwork',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='usermusicartist',
            name='user_music_artist_idx',
        ),
        migrations.RemoveIndex(
            model_name='usermusicpiece',
            name='user_music_idx',
        ),
        migrations.RemoveField(
            model_name='usermusicartist',
            name='person',
        ),
        migrations.RemoveField(
            model_name='usermusicpiece',
            name='universal_item',
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='lists',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='usermusicpiece',
            name='artist',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usermusicpiece',
            name='instrument',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usermusicpiece',
            name='recording',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermusicpiece',
            name='sheet_music',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermusicpiece',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddIndex(
            model_name='usermusicartist',
            index=models.Index(fields=['user'], name='user_music_artist_idx'),
        ),
        migrations.AddIndex(
            model_name='usermusicpiece',
            index=models.Index(fields=['user'], name='user_music_idx'),
        ),
        migrations.DeleteModel(
            name='Artwork',
        ),
        migrations.DeleteModel(
            name='MusicPiece',
        ),
        migrations.DeleteModel(
            name='UserArtwork',
        ),
    ]
