# Generated by Django 5.2.5 on 2025-10-27 11:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_remove_artwork_creator_remove_artwork_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMusicComposer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('notes', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('alt_name', models.CharField(blank=True, max_length=200, null=True)),
                ('occupations', models.JSONField(blank=True, default=list, null=True)),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('death_year', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('photo', models.URLField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('famous', models.JSONField(blank=True, default=list, null=True)),
                ('themes', models.JSONField(blank=True, default=list, null=True)),
                ('instruments', models.JSONField(blank=True, default=list, null=True)),
                ('cultures', models.ManyToManyField(blank=True, related_name='%(class)s_items', to='core.culture')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='composers', to='core.period')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Composers',
                'indexes': [models.Index(fields=['user'], name='user_composer_idx')],
            },
        ),
    ]
