# Generated by Django 5.2.5 on 2025-10-27 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_usermusiccomposer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermusiccomposer',
            name='location',
        ),
    ]
