# Generated by Django 5.2.5 on 2025-10-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_remove_usermusiccomposer_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermusicpiece',
            name='instrument',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usermusicpiece',
            name='sheet_music',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
