# Generated by Django 5.2.5 on 2025-10-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_usermusicpiece_instrument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermusicpiece',
            name='release_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
