# Generated by Django 5.2.5 on 2025-10-28 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_usermusicpiece_release_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserComposerSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('composer_list', models.JSONField(blank=True, default=list, null=True)),
                ('saved_location', models.JSONField(blank=True, default=dict, null=True)),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.culture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Composer Searches',
                'indexes': [models.Index(fields=['user', 'culture'], name='user_composer_search_idx')],
                'unique_together': {('user', 'culture')},
            },
        ),
    ]
