# Generated by Django 5.2.5 on 2025-10-28 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_usercomposersearch'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calendardate',
            unique_together={('holiday_name', 'calendar_date')},
        ),
    ]
