# Generated by Django 5.2.5 on 2025-10-29 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_alter_calendardate_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMapPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('center', models.JSONField(blank=True, default=dict, null=True)),
                ('zoom', models.PositiveIntegerField(blank=True, default=5, null=True)),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_preferences', to='core.culture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Map Preferences',
            },
        ),
        migrations.DeleteModel(
            name='MapBorder',
        ),
    ]
