# Generated by Django 5.2.5 on 2025-10-29 17:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_usermappreferences_delete_mapborder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappin',
            name='culture',
        ),
        migrations.AddField(
            model_name='mappin',
            name='cultures',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_items', to='core.culture'),
        ),
        migrations.AddField(
            model_name='mappin',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mappin',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='mappin',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
