# Generated by Django 5.2.5 on 2025-10-29 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_remove_mappin_culture_mappin_cultures_mappin_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappin',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='map_pins', to='core.period'),
        ),
    ]
