# Generated by Django 5.2.5 on 2025-10-30 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_alter_mappin_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappin',
            name='filter',
            field=models.CharField(blank=True, choices=[('landmark', 'Landmark'), ('event', 'Event'), ('travel', 'Travel'), ('figure', 'Figure'), ('artwork', 'Artwork'), ('other', 'Other')], default='other', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mappin',
            name='date',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_map_pin', to='core.dateestimate'),
        ),
    ]
