# Generated by Django 5.2.5 on 2025-10-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_mappin_filter_alter_mappin_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappin',
            name='filter',
            field=models.CharField(choices=[('landmark', 'Landmark'), ('event', 'Event'), ('travel', 'Travel'), ('figure', 'Figure'), ('artwork', 'Artwork'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='mappin',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
