# Generated by Django 5.2.5 on 2025-10-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_alter_mappin_filter_alter_mappin_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappin',
            name='external_links',
        ),
        migrations.AddField(
            model_name='mappin',
            name='external_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
