# Generated by Django 5.2.5 on 2025-10-31 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_remove_mappin_external_links_mappin_external_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culture',
            name='picture',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
