# Generated by Django 5.2.5 on 2025-10-31 22:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_alter_culture_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calendardate',
            unique_together={('holiday_name', 'calendar_date', 'user')},
        ),
    ]
