# Generated by Django 5.2.5 on 2025-11-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_alter_calendardate_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='runtime',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
