# Generated by Django 5.2.5 on 2025-11-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_alter_film_runtime'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE core_film DROP CONSTRAINT IF EXISTS core_film_runtime_check;
            """,
            reverse_sql="""
                ALTER TABLE core_film ADD CONSTRAINT core_film_runtime_check
                CHECK (runtime >= 0);
            """,
        ),
        migrations.RunSQL(
            # Forward: integer (minutes) → interval
            sql="""
                ALTER TABLE core_film
                ALTER COLUMN runtime TYPE interval
                USING runtime * interval '1 minute';
            """,
            # Reverse: interval → integer (minutes)
            reverse_sql="""
                ALTER TABLE core_film
                ALTER COLUMN runtime TYPE integer
                USING (EXTRACT(epoch FROM runtime) / 60)::integer;
            """,
        ),
        # Now make it a proper DurationField (Django metadata)
        migrations.AlterField(
            model_name='film',
            name='runtime',
            field=models.DurationField(blank=True, null=True),
        ),
        # Re-add correct interval-based CHECK
        migrations.RunSQL(
            sql="""
                ALTER TABLE core_film ADD CONSTRAINT core_film_runtime_check
                CHECK (runtime >= '0'::interval);
            """,
            reverse_sql="""
                ALTER TABLE core_film DROP CONSTRAINT IF EXISTS core_film_runtime_check;
            """,
        ),
    ]
